# -*- Makefile -*-
#
# Common Makefile for building RPMs
# Licensed under the new-BSD license (http://www.opensource.org/licenses/bsd-license.php)
# Copyright (C) 2004-2005 Red Hat, Inc.
# Copyright (C) 2005 Fedora Foundation
#
# $Id: Makefile.common,v 1.14 2022/06/08 18:44:49 jpp Exp $

.DEFAULT_GOAL := help
# Define the common dir.
# This needs to happen first.
define find-common-dir
for d in common ../common ../../common ; do if [ -f $$d/Makefile.common ] ; then echo "$$d"; break ; fi ; done
endef
COMMON_DIR := $(shell $(find-common-dir))
# check if Makefile.common is up-to-date
$(COMMON_DIR)/Makefile.common: common-sync-check
    @:

# if not up-to-date synchronise with git and reload
.PHONY: common-sync-check
common-sync-check:
	@if [ -d "$(COMMON_DIR)/.git" ]; then \
	    if cd $(COMMON_DIR) && git status --porcelain 2>/dev/null | grep -q . ; then \
		echo "WARNING: $(COMMON_DIR) has unstaged or uncommitted changes!" >&2 ; \
		echo "         Skipping automatic update to preserve your local modifications." >&2 ; \
	    else \
		cd $(COMMON_DIR) && git fetch -q origin 2>/dev/null ; \
		LOCAL_HASH=$$(cd $(COMMON_DIR) && git rev-parse HEAD 2>/dev/null) ; \
		REMOTE_HASH=$$(cd $(COMMON_DIR) && git rev-parse @{u} 2>/dev/null) ; \
		if [ "$$LOCAL_HASH" != "$$REMOTE_HASH" ]; then \
		    echo "NOTICE: $(COMMON_DIR) is outdated! Pulling down current rules..." >&2 ; \
		    cd $(COMMON_DIR) && git pull --rebase -q ; \
		    echo "Successfully updated $(COMMON_DIR). Reloading Makefile..." >&2 ; \
		fi \
	    fi \
	fi

# Branch and disttag definitions
# These need to happen second.
ifndef HEAD_BRANCH
HEAD_BRANCH := devel
endif
BASEDIR := $(shell basename `pwd`)

# Capture any of your exact or wildcard build targets passed to the command line
ACTIVE_BUILD_GOALS := $(filter build chain-build scratch-build scratch-build-% tagbuild,$(MAKECMDGOALS))

# Automatically inject the workspace status check and target validation steps
$(eval $(if $(ACTIVE_BUILD_GOALS), \
    $(foreach t,$(ACTIVE_BUILD_GOALS), \
        $(t): repo-clean-check target-check branch-check \
    ) \
))

# get and store the current GIT information for later use
# using git
#GIT_BRANCH = $(shell git branch --list | cut -d' ' -f2)
# without git installed eg in chroot
GIT_BRANCH = $(shell cat .git/HEAD 2>/dev/null | sed 's|.*/||')
GIT_BRANCHES := $(shell git branch -a | sed -E 's|[* ]||g; s|remotes/origin/||g; s|HEAD->origin/master||g; /^$$/d' | sort -u 2>/dev/null)
#GIT_LOCAL_BRANCHES := $(shell git branch --list | sed 's/[* ]//g' 2>/dev/null)
PREF = $(shell [ `grep url -r .git/config | cut -d/ -f4` == "smecontribs" ] && echo 'contribs' || echo 'sme')
CURRENT = $(shell cat $(COMMON_DIR)/current)
# using git
COMMIT_URL := $(shell git config --get remote.origin.url 2>/dev/null | \
    sed -E 's|ssh://gitea@git\.koozali\.org:2222/|https://src.koozali.org/|')/src/commit/$(shell git rev-parse HEAD 2>/dev/null)

# If a 2nd parameter passed, assume it is a TARGET
# Will allow build from individual branch if the HEAD specifies a TARGET in the common/branches file (e.g. sme11 or contribs11)
# Defaults to versions contained in file common/current if HEAD=master (with prefix of either sme or contribs based on GITEA organisation)
# Check if GIT_BRANCH starts with "sme" or "contribs" and issue a WARNING
POSSIBLE_TARGET := $(wordlist 2,$(words $(MAKECMDGOALS)),$(MAKECMDGOALS))
VALID_TARGETS := $(shell cut -d: -f1 $(COMMON_DIR)/branches 2>/dev/null)
# If it's a switch check that the target git branch exists
ifeq ($(firstword $(MAKECMDGOALS)),switch)
  NEW_BRANCH := $(POSSIBLE_TARGET)
  ifneq ($(strip $(NEW_BRANCH))),)
    $(NEW_BRANCH):
    @:
  endif
  ifeq ($(filter $(NEW_BRANCH),$(GIT_BRANCHES)),)
    $(error Error: Branch '$(NEW_BRANCH)' does not exist. Run 'git branch --list' to see valid branches.)
  endif
  TARGET = $(addprefix $(PREF),$(CURRENT))
else
  ifneq ($(filter $(POSSIBLE_TARGET),$(VALID_TARGETS)),)
    TARGET = $(POSSIBLE_TARGET)
  endif
  ifneq ($(strip $(TARGET)),)
    ifneq ($(filter $(GIT_BRANCH),$(VALID_TARGETS)),)
      $(info WARNING: you are overiding the Branch default Target of $(GIT_BRANCH) with $(TARGET)) 
    endif
  else
    ifeq ($(GIT_BRANCH),master)
      TARGETS_PRESENT := $(strip $(filter $(GIT_BRANCHES),$(VALID_TARGETS)))
      ifneq ($(TARGETS_PRESENT),)
        TARGET = $(addprefix $(PREF),$(word 1,$(CURRENT)))
        $(info WARNING: you have some valid target git branches ($(TARGETS_PRESENT)), so defaulting to primary current target ONLY ($(TARGET)))
      else
        TARGET = $(addprefix $(PREF),$(CURRENT))
      endif
    else
      ifneq ($(filter $(GIT_BRANCH),$(VALID_TARGETS)),)
        TARGET = $(GIT_BRANCH)
      else
        TARGET = $(addprefix $(PREF),$(CURRENT))
      endif
    endif
  endif
endif
# check list of TARGETs against common/branches to check that they exist
INVALID_TARGETS := $(filter-out $(VALID_TARGETS),$(TARGET))
ifneq ($(firstword $(MAKECMDGOALS)),switch)
# Check if TARGET is completely empty
ifeq ($(strip $(TARGET)),)
    $(error No valid TARGET for $(BRANCH) found)
endif
# Check if there are any invalid targets in the list
ifneq ($(strip $(INVALID_TARGETS)),)
    $(error Unknown TARGET(s): $(INVALID_TARGETS))
endif
endif

BRANCH = $(word 1, $(TARGET))
# check BRANCH against common/branches to ensure that it exists
branch-check:
	@if ! grep -q "$(BRANCH)" $(COMMON_DIR)/branches; then echo "Unknown BRANCH '$(BRANCH)'" ; exit 1; fi

$(eval $(if $(filter %build,$(MAKECMDGOALS)), $(foreach t,$(filter %build,$(MAKECMDGOALS)), $(t): branch-check)))

# grab all the requierd info from common/branches for this BRANCH
BRANCHINFO := $(shell grep ^$(BRANCH): $(COMMON_DIR)/branches | cut -d: --output-delimiter=" " -f2-)
DIST = $(word 2, $(BRANCHINFO))
DISTVAR = $(word 3, $(BRANCHINFO))
DISTVAL = $(word 4, $(BRANCHINFO))
DISTDEF = $(shell echo  $(DIST) | sed -e s/^\\\.//| sed -e s/\\\./_/ )
SMEVAL = $(word 5, $(BRANCHINFO))
DIST_DEFINES = --define "dist $(DIST)" --define "$(DISTVAR) $(DISTVAL)" --define "$(DISTDEF) 1" --define "sme $(SMEVAL)"

BUILD_FLAGS ?= $(KOJI_FLAGS)

LOCALARCH := $(if $(shell grep -i '^BuildArch:.*noarch' $(SPECFILE)), noarch, $(shell uname -m))

# use TARGET for this BRANCH from common/branches unless defined/passed as parameter
ifndef TARGET
TARGET = $(word 1, $(BRANCHINFO))
endif

$(eval $(if $(filter %build,$(MAKECMDGOALS)), $(foreach t,$(filter %build,$(MAKECMDGOALS)), $(t): target-check)))

# a base directory where we'll put as much temporary working stuff as we can
ifndef WORKDIR
WORKDIR := $(shell pwd)
endif
# of course all this can also be overridden in your RPM macros file,
# but this way you can separate your normal RPM setup from your CVS
# setup. Override RPM_WITH_DIRS in ~/.cvspkgsrc to avoid the usage of
# these variables.
SRCRPMDIR ?= $(WORKDIR)
BUILDDIR ?= $(WORKDIR)
RPMDIR ?= $(WORKDIR)
MOCKDIR ?= $(WORKDIR)
MOCKCFG ?= smeserver-$(SMEVAL)-$(BUILDARCH)-base
# SOURCEDIR is special; it has to match the CVS checkout directory, 
# because the CVS checkout directory contains the patch files. So it basically 
# can't be overridden without breaking things. But we leave it a variable
# for consistency, and in hopes of convincing it to work sometime.
ifndef SOURCEDIR
SOURCEDIR := $(shell pwd)
endif
ifndef SPECDIR
SPECDIR := $(shell pwd)
endif

ifndef RPM_DEFINES
RPM_DEFINES := --define "_sourcedir $(SOURCEDIR)" \
		--define "_specdir $(SPECDIR)" \
		--define "_builddir $(BUILDDIR)" \
		--define "_srcrpmdir $(SRCRPMDIR)" \
		--define "_rpmdir $(RPMDIR)" \
                $(DIST_DEFINES)
endif

# Initialize the variables that we need, but are not defined
# the version of the package
VER_REL := $(shell rpm $(RPM_DEFINES) $(DIST_DEFINES) -q --qf "%{VERSION} %{RELEASE}\n" --specfile $(SPECFILE)| head -1)
ifndef NAME
$(error "You can not run this Makefile without having NAME defined")
endif
ifndef VERSION
VERSION := $(word 1, $(VER_REL))
endif
# the release of the package
ifndef RELEASE
RELEASE := $(word 2, $(VER_REL))
endif
#$(info $$VER_REL is ${VER_REL} version is ${VERSION})
# this is used in make patch, maybe make clean eventually.
# would be nicer to autodetermine from the spec file...
RPM_BUILD_DIR ?= $(BUILDDIR)/$(NAME)-$(VERSION)

#needed for archivefile rule
TREEPATH := $(NAME)-$(VERSION)
CODEDIR := "root"
TEMPDIR := $(shell mktemp -d) 
EXT := $(shell cat $(NAME).spec | grep -e '^[S|s]ource' | head -n 1 | sed 's/Source: //' | sed -E 's/^([^.]*\.)(.*)$/\2//')
#ARCHIVEFILE=$(cat ${NAME}.spec | grep -e '^[S|s]ource' | sed -r 's/^[S|s]ource[0-9]?:\s?//' | xargs basename)
#ARCHIVEFILE=$(rpm --queryformat "${ARCHIVEFILE}\n" --specfile ${NAME}.spec | head -n 1)
#ifeq (,$(wildcard archivefilename))
#ARCHIVEFILE := "$(NAME)-$(VERSION).tar.gz"
#else
#ARCHIVEFILE := $(shell cat archivefilename)
#endif
#ARCHIVEFILE := $(shell cat $(NAME).spec | grep -e '^[S|s]ource' | sed -r 's/^[S|s]ource[0-9]?:\s?//' | sed -e 's/{//g' -e 's/}//g' -e "s/%name/$(NAME)/g" -e "s/%version/$(VERSION)/g" | xargs basename)
# we expect archive tgz gz or xz
ARCHIVEFILE := $(shell cat $(NAME).spec | grep -e '^[S|s]ource' | sed -r 's/^[S|s]ource[0-9]?:\s?//' | sed -e 's/\s//g' -e 's/{//g' -e 's/}//g' -e "s/%name/$(NAME)/g" -e "s/%version/$(VERSION)/g" |grep -E "z$$" | xargs basename)
#$(info $$VER_REL is ${VER_REL} version is ${VERSION} ARCHIVEFILE is ${ARCHIVEFILE})

# default target: 
all: 

# The repository and the clients we use for the files
REPOSITORY ?= http://buildsys.contribs.org/source
UPLOAD_REPOSITORY ?= /build/builds/source

# We define CURL and WGET in a way that makes if possible to have them
# overwritten from the module's Makefiles. Then CLIENT picks CURL, otherwise WGET
CURL	?= $(shell if test -f /usr/bin/curl ; then echo "curl -H Pragma: -O -R -S --fail --show-error" ; fi)
WGET	?= $(shell if test -f /usr/bin/wget ; then echo "wget -nd -m" ; fi)
CLIENT	?= $(if $(CURL),$(CURL),$(if $(WGET),$(WGET)))
PLAGUE_CLIENT ?= $(shell which plague-client 2>/dev/null)
BUILD_CLIENT ?= $(shell which koji 2>/dev/null)
BODHI_CLIENT ?= $(shell which bodhi 2>/dev/null)

# RPM with all the overrides in place; you can override this in your
# .cvspkgsrc also, to use a default rpm setup
# the rpm build command line
ifndef RPM
RPM := rpmbuild
endif
ifndef RPM_WITH_DIRS
RPM_WITH_DIRS = $(RPM) $(RPM_DEFINES)
endif

# CVS-safe version/release -- a package name like 4Suite screws things
# up, so we have to remove the leaving digits from the name
#TAG_NAME    := $(shell echo $(NAME)    | sed -e s/\\\./_/g -e s/^[0-9]\\\+//g)
#TAG_VERSION := $(shell echo $(VERSION) | sed s/\\\./_/g)
#TAG_RELEASE := $(shell echo $(RELEASE) | sed s/\\\./_/g)
TAG_NAME    := $(NAME)
TAG_VERSION := $(VERSION)
TAG_RELEASE := $(RELEASE)

# tag to export, defaulting to current tag in the spec file
#TAG?=$(TAG_NAME)-$(TAG_VERSION)-$(TAG_RELEASE)
# simpler tagging using GIT
TAG?=$(TAG_VERSION)-$(TAG_RELEASE)

#TODO remove was CVS specific # retrieve the stored md5 sum for a source download
define get_sources_md5
$(shell cat sources 2>/dev/null | while read m f ; do if test "$$f" = "$@" ; then echo $$m ; break ; fi ; done)
endef

# list the possible targets for valid arches
ARCHES = noarch i686 x86_64 aarch64 # i386 i586 ia64 s390 s390x ppc ppc64 pseries ppc64pseries iseries ppc64iseries athlon alpha alphaev6 sparc sparc64 sparcv9 sparcv9v sparc64v i164 mac sh mips geode

# for the modules that do different "make prep" depending on what arch we build for
PREP_ARCHES	= $(addprefix prep-,$(ARCHES))

# list all our bogus targets
.PHONY : $(ARCHES) $(ARCHIVEFILE) clog commit commiturl giturl tagurl sources uploadsource upload check build build-check branch-check target-check plague koji build chain-build test-srpm srpm tag tagbuild force-tag verrel new clean patch prep compile install install-short compile-short FORCE local scratch-build showinfo switch_branch scratch-build-%

# The TARGETS define is meant for local module targets that should be
# made in addition to the SOURCEFILES whenever needed
TARGETS		?= $(ARCHIVEFILE)
#TARGETS		?= 

# default target - retrieve/rebuild the sources and make the module specific targets
sources:  $(TARGETS)

# allow overriding buildarch so you can do, say, an i386 build on x86_64
ifndef BUILDARCH
BUILDARCH := $(shell rpm --eval "%{_arch}")
endif

# Safety check target
.PHONY: repo-clean-check
## repo-clean-check: Check that the repo is clean
repo-clean-check:
	@if git status --porcelain 2>/dev/null | grep -q . ; then \
	    echo "WARNING: Your git repository has uncommitted changes or untracked files!" >&2 ; \
#	    echo "ERROR: Your git repository has uncommitted changes or untracked files!" >&2 ; \
	    echo "Please commit, stash, or delete them before running a build." >&2 ; \
	    echo "" >&2 ; \
	    git status -s >&2 ; \
	    echo "" >&2 ; \
#	    exit 1 ; \
	fi

# test build in moc
## mockbuild: Local test build using mock (make mockbuild)k
mockbuild : srpm
	mock $(MOCKARGS) -r $(MOCKCFG) --resultdir=$(MOCKDIR)/$(TAG) rebuild $(SRCRPMDIR)/$(NAME)-$(VERSION)-$(RELEASE).src.rpm

# check the build with rpmlint
## lint: Check the build with rpmlint
lint:
	@test -e $(NAME)-$(VERSION)-$(RELEASE).src.rpm || (echo "run 'make local' first" ; exit 1 )
	rpmlint $(NAME)-$(VERSION)-$(RELEASE).src.rpm $(LOCALARCH)/*-$(VERSION)-$(RELEASE).$(LOCALARCH).rpm

# build for a particular arch
$(ARCHES) : sources $(TARGETS)
	$(RPM_WITH_DIRS) --target $@ -ba $(SPECFILE) 2>&1 | tee .build-$(VERSION)-$(RELEASE).log ; exit $${PIPESTATUS[0]}

# empty target to force checking 
FORCE:

## local: build whatever's appropriate for the local architecture
local: $(LOCALARCH)

## prep: attempt to apply all the patches, optionally only for a particular arch
ifdef PREPARCH
prep: sources $(TARGETS)
	$(RPM_WITH_DIRS) --nodeps -bp --target $(PREPARCH) $(SPECFILE)
else
prep: sources $(TARGETS)
	$(RPM_WITH_DIRS) --nodeps -bp $(SPECFILE)
endif

## prep-%: this allows for make prep-i686, make prep-ppc64, etc
prep-% : Makefile
	$(MAKE) prep PREPARCH=$*

## compile: Local test - rpmbuild compile
compile: sources $(TARGETS)
	$(RPM_WITH_DIRS) -bc $(SPECFILE)

## install: local test - rpmbuild install
install: sources $(TARGETS)
	$(RPM_WITH_DIRS) -bi $(SPECFILE)

## compile-short: Local test - rpmbuild short-circuit compile 
compile-short: sources $(TARGETS)
	$(RPM_WITH_DIRS) --nodeps --short-circuit -bc $(SPECFILE)

## install-short: Local test - rpmbiuild short-circuit install
install-short: sources $(TARGETS)
	$(RPM_WITH_DIRS) --nodeps --short-circuit -bi $(SPECFILE)

#TODO remove was CVS specific
CVS_ROOT	:= $(shell if [ -f CVS/Root ] ; then cat CVS/Root ; fi)
# get the url from .git/config, prefix with git+ and append TAG for koji building
RAW_URL     := $(shell grep url -r .git/config | cut -d= -f2 | sed 's/^[[:space:]]*//')
#GIT_URL     := git+$(RAW_URL)\#$(TAG)
GIT_REPOSITORY := $(shell basename $(RAW_URL))
GIT_ORG := $(shell basename `dirname $(RAW_URL)`)
# some people will clone from ssh and some from https.
# koji has only read https access. Also, src.koozali.org points to the https
# while git.koozali.org, for ssh, points to a different ip 
GIT_URL     := git+https://src.koozali.org/$(GIT_ORG)/$(GIT_REPOSITORY)\#$(TAG)

## check: build a test-srpm and see if it will -bp on all arches 
# XXX: I am not sure exactly what this is supposed to really do, since the
# query format returns (none) most of the time, and that is not
# handled --gafton
check: test-srpm
	@archs=`rpm -qp $(SRCRPMDIR)/$(NAME)-$(VERSION)-$(RELEASE).src.rpm --qf "[%{EXCLUSIVEARCH}\n]" | egrep -v "(i586)|(i686)|(athlon)"` ;\
	if test -z "$$archs"; then archs=noarch; fi ; \
	echo "Checking arches: $$archs" ; \
	for arch in $$archs; do \
	    echo "Checking $$arch..."; \
	    if ! $(RPM_WITH_DIRS) -bp --target $$arch $(SPECFILE); then \
		echo "*** make prep failed for $$arch"; \
		exit 1; \
	    fi; \
	done;

## srpm: Use this to build an srpm locally
ifneq (, $(filter contribs7 contribs8 contribs9, $(BRANCH)))
srpm: sources $(TARGETS)
	$(RPM_WITH_DIRS) $(DIST_DEFINES) --define _source_filedigest_algorithm=md5 --nodeps -bs $(SPECFILE)
else
srpm: sources $(TARGETS)
	$(RPM_WITH_DIRS) $(DIST_DEFINES) --nodeps -bs $(SPECFILE)
endif

# Create the .tar.gz or whatever file
$(ARCHIVEFILE):
ifneq (, $(shell which git))
	$(info create or update ${ARCHIVEFILE} archive)
	@mkdir -p "${TEMPDIR}/${TREEPATH}" ;\
	if [ -d ${CODEDIR} ] ; then cp -R "${CODEDIR}" "${TEMPDIR}/${TREEPATH}" ; fi ; \
	if [ -e createlinks ] ; then cp createlinks "${TEMPDIR}/${TREEPATH}/." ; fi ; \
	if [ -d additional ] ; then cp -r additional/* "${TEMPDIR}/${TREEPATH}/." ; fi ; \
	find "${TEMPDIR}/${TREEPATH}/." -type f -name ".gitignore" -delete ; \
	git ls-files --error-unmatch ${ARCHIVEFILE} 2>/dev/null || rm -f ${ARCHIVEFILE} ;\
	git ls-files --error-unmatch ${ARCHIVEFILE} 2>/dev/null || tar -caf "${ARCHIVEFILE}" -C "${TEMPDIR}" "${TREEPATH}" ;\
	ls -l ${ARCHIVEFILE} ;\
	rm -Rf "${TEMPDIR}/${TREEPATH}/"
else
	@mkdir -p "${TEMPDIR}/${TREEPATH}" ;\
	if [ -d ${CODEDIR} ] ; then cp -R "${CODEDIR}" "${TEMPDIR}/${TREEPATH}" ; fi ; \
	if [ -e createlinks ] ; then cp createlinks "${TEMPDIR}/${TREEPATH}/." ; fi ; \
	if [ -d additional ] ; then cp -r additional/* "${TEMPDIR}/${TREEPATH}/." ; fi ; \
	find "${TEMPDIR}/${TREEPATH}/." -type f -name ".gitignore" -delete ; \
	[ -f ${ARCHIVEFILE} ] || tar -caf "${ARCHIVEFILE}" -C "${TEMPDIR}" "${TREEPATH}" ;\
	ls -l ${ARCHIVEFILE} ;\
	rm -Rf "${TEMPDIR}/${TREEPATH}/"
	$(info keeping ${ARCHIVEFILE} archive if exist (Builder mock))
endif

## test-srpm: same as srpm
test-srpm: srpm

## verrel: Display <name>-<version>-<release> of this pkg
verrel:
	@echo $(NAME)-$(VERSION)-$(RELEASE)

# showinfo: Display values of some of the key calculated variables
showinfo:
	$(info $$PREF is ${PREF})
	$(info $$GIT_URL is ${GIT_URL}) 
	$(info $$GIT_BRANCH is ${GIT_BRANCH})
	$(info $$GIT_BRANCHES are ${GIT_BRANCHES})
	$(info $$BRANCH is ${BRANCH}) 
	$(info $$BRANCH_INFO is ${BRANCHINFO})
	$(info $$TARGET is ${TARGET})
	$(info $$VER_REL is ${VER_REL})
	$(info $$NAME is ${NAME})
	$(info $$VERSION is ${VERSION})
	$(info $$RELEASE is ${RELEASE})
	$(info COMMIT is $(notdir $(COMMIT_URL)))
#	$(info COMMIT URL is $(shell $(MAKE) --no-print-directory commiturl))
	@:

# If you build a new version into the tree, first do "make tag",
# then "make srpm", then build the package.  
TAG_ACTIONS := $(addprefix run-tag-,$(TARGET))
## tag: create a new git tag from your specfile and push to gitea
tag: $(SPECFILE) $(COMMON_DIR)/branches $(TAG_ACTIONS)
	git push --tag

.PHONY: run-tag-%
run-tag-%:
	@elver=$$(awk -F: -v target="$*" '$$1 == target { split($$0, fields, ":"); print fields[5] }' $(COMMON_DIR)/branches) ; \
	if [ -z "$$elver" ]; then echo "Unknown TARGET '$*'"; exit 1; fi ; \
	expanded_tag=$$(echo "$(VERSION)-$(RELEASE)" | sed "s/\.el./.el$$elver/") ; \
	\
	# Check if the tag already exists in your local Git repository \
	if git rev-parse "refs/tags/$$expanded_tag" >/dev/null 2>&1; then \
	    echo "ERROR: The tag '$$expanded_tag' already exists locally!" >&2 ; \
	    echo "- have you updated/committed the spec file?" >&2 ; \
	    exit 1; \
	fi ; \
	\
	# Check if the tag already exists on the remote Git server (origin) \
	if git ls-remote --tags origin "refs/tags/$$expanded_tag" 2>/dev/null | grep -q . ; then \
	    echo "ERROR: The tag '$$expanded_tag' already exists on the remote server (origin)!" >&2 ; \
	    echo "- have you updated/committed the spec file?" >&2 ; \
	    exit 1; \
	fi ; \
	\	
	git tag $(TAG_OPTS) -a $$expanded_tag -m $$expanded_tag ; \
	echo "Successfully tagged $* with: $$expanded_tag"

## tagbuild: Will run tag, build, clog, tagurl
tagbuild: tag  build clog commiturl tagurl
	@rm -f clog

force-tag: $(SPECFILE) $(COMMON_DIR)/branches
	@$(MAKE) tag TAG_OPTS="-F $(TAG_OPTS)"

define find-user
if [ -f CVS/Root ] ; then if [ `cat CVS/Root |grep -c [^:]@` -ne 0 ]; then cat CVS/Root  |cut -d @ -f 1 |  sed 's/:.*://' ; else echo $(USER); fi ; else echo $(USER);fi
endef
USER := $(shell $(find-user))

build-check: $(SPECFILE)
	@git tag 2>/dev/null | grep -q $(TAG); ret=$$? ;\
	if [ $$ret -ne 0 ]; then echo "$(SPECFILE) not tagged with tag $(TAG)"; exit 1;  fi

KOJI_ACTIONS := $(addprefix koji-build-,$(TARGET))
koji: build-check $(COMMON_DIR)/branches $(KOJI_ACTIONS)

.PHONY: koji-tool-check
koji-tool-check:
	@if [ ! -x "$(BUILD_CLIENT)" ]; then \
	    echo "Must have koji installed - see https://fedoraproject.org/wiki/BuildSystemClientSetup"; \
	    exit 1; \
	fi

.PHONY: koji-build-%
koji-build-%: koji-tool-check
	@elver=$$(awk -F: -v target="$*" '$$1 == target { print $$5 }' $(COMMON_DIR)/branches) ; \
	if [ -z "$$elver" ]; then echo "Unknown TARGET '$*'"; exit 1; fi ; \
	expanded_url=$$(echo "$(GIT_URL)" | sed "s/\.el./.el$$elver/") ; \
	$(BUILD_CLIENT) $(SECONDARY_CONFIG) build --nowait $(BUILD_FLAGS) "$*" "$$expanded_url"

## build: Request a build on koji for specified TARGET
##     Usage: make build or make build <target> or make build TARGET=<target>
##     Example: make build
##     will trigger a build on koji for all arches with a TARGET=<default target> - see make help for more info
##     Example: make build sme12 or make build TARGET=sme12
##     will trigger a build on koji for all arches with a TARGET=sme12
build: koji
#else
#build: plague
#endif

# scratch-build will only use the first target and ignore all others (if it gets this far)
## scratch-build: Request a scratch-build on koji for the specifief TARGET
##     Usage:   make scratch-build <target>
##     Example: make scratch-build sme12
##     will trigger a scratch build on koji using the sme12-build for all arches 
scratch-build: build-check
	@if [ ! -x "$(BUILD_CLIENT)" ]; then echo "Must have koji installed - see http://fedoraproject.org/wiki/BuildSystemClientSetup"; exit 1; fi
	$(eval SCRATCH_TARGET := $(firstword $(TARGET)))
	$(BUILD_CLIENT) $(SECONDARY_CONFIG) build --scratch $(BUILD_FLAGS) $(SCRATCH_TARGET) '$(GIT_URL)'

# TODO Target checking is not performed for scratch-build-<arch>
# scratch-build will only use the first target and ignore all others (if it gets this far)
## scratch-build-%: Request a scratch-build on koji for the specified TARGET and arch
##     Usage:   make scratch-build-<arch> <target>
##     Example: make scratch-build-aarm64 sme12
##     will trigger a scratch build on koji using the sme12-build but only for aarch64 
scratch-build-%: build-check
	@if [ ! -x "$(BUILD_CLIENT)" ]; then echo "Must have koji installed - see http://fedoraproject.org/wiki/BuildSystemClientSetup"; exit 1; fi
	$(eval SCRATCH_TARGET := $(firstword $(TARGET)))
	$(BUILD_CLIENT) $(SECONDARY_CONFIG) build --scratch --arch-override=$* $(BUILD_FLAGS) $(SCRATCH_TARGET) '$(GIT_URL)'

# TODO rework or remove
bodhi: build-check $(COMMON_DIR)/branches clog 
	@if [ ! -x "$(BODHI_CLIENT)" ]; then echo "Must have bodhi-client installed"; exit 1; fi
	@echo -e "\
# [ $(NAME)-$(VERSION)-$(RELEASE) ]\n\
# type=[S|B|E] (S=security, B=bugfix, E=enhancement) (required)\n\
# request=[T|S] (T=testing, S=stable) (default: testing)\n\
# bug=123,456\n\
# all other text will be considered to be part of the update notes\n\
type=" > bodhi.template
	@grep -iZ '\[SME' clog | xargs -0n1 | sed -n -e 's,[^]]*\[SME[: ]*\([0-9]*\)\],\1 ,igp' | xargs | tr ' ' ',' > $(NAME).bugs
	@if [ `cat $(NAME).bugs` ]; then echo "bug=`cat $(NAME).bugs`" >> bodhi.template; fi
	@sed -e '/^#/d' < bodhi.template > bodhi.template.orig
	@if [ -z "$$EDITOR" ]; then vi bodhi.template; else $$EDITOR bodhi.template; fi
	@if [ -n "`sed -e '/^#/d' < bodhi.template | diff bodhi.template.orig -`" ]; then \
		$(BODHI_CLIENT) -v --new --release $(subst -,,$(BRANCH)) \
			--file bodhi.template $(NAME)-$(VERSION)-$(RELEASE) -u $(BODHI_USER); \
	else \
		echo "Bodhi update aborted!"; \
	fi
	@rm -f bodhi.template{,.orig} $(NAME).bugs clog

ifndef $(BODHI_USER)
BODHI_USER=$(USER)
endif

ifneq (, $(filter contribs7 contribs8 contribs9, $(BRANCH)))
update: bodhi
endif

## giturl: Display the git url
giturl:
	 @echo '$(GIT_URL)'

## commiturl: Display the url for the current commit
commiturl:
	@echo '$(COMMIT_URL)'

## tagurl: Display the url for the current git tag
tagurl:
	@BASE_URL=$$(git config --get remote.origin.url | sed -E 's|ssh://gitea@git\.koozali\.org:2222/|https://src.koozali.org/|' | sed 's/\.git$$//'); \
	TAGS=$$(git log --tags --simplify-by-decoration --pretty="format:%d" | grep -o 'tag: [^,)]*' | sed 's/tag: //' | head -n 2); \
	TAG_RECENT=$$(echo "$$TAGS" | sed -n '1p'); \
	TAG_ANCIEN=$$(echo "$$TAGS" | sed -n '2p'); \
	if [ -z "$$TAG_ANCIEN" ] || [ -z "$$TAG_RECENT" ]; then \
		echo "Erreur : Impossible de trouver au moins deux tags sur cette branche."; \
	else \
		echo "$$BASE_URL/compare/$$TAG_ANCIEN..$$TAG_RECENT"; \
	fi

# TODO rework or remove
## chain-build: Build multiple dependent packages in a sequential Koji chain
##     Usage:   make chain-build CHAIN="<pkg1> <pkg2> ..." [ TARGET=<target> ]
##     Example: make chain-build CHAIN="libwidget libgizmo" TARGET=sme12
##     The current package is added to the end of the CHAIN list.
##     Colons (:) can be used in the CHAIN parameter to define dependency groups.
##     Packages in a single group will be built in parallel, and all packages
##     in a group must build successfully and populate the repository before
##     the next group will begin building.
##     If no groups are defined, packages will be built sequentially.
chain-build: build-check
	@if [ -z "$(CHAIN)" ]; then \
                echo "Missing CHAIN variable, please specify the order of packages to" ; \
                echo "chain build.  For example:  make chain-build CHAIN='foo bar'" ; \
                exit 1 ; \
        fi ; \
        set -e ; \
        subdir=`basename $$(pwd)` ; \
        urls="" ; \
        for component in $(CHAIN) ; do \
                if [ "$$component" = "$(NAME)" ]; then \
                        echo "$(NAME) must not appear in CHAIN" ; \
                        exit 1 ; \
                fi ; \
                if [ "$$component" = ":" ]; then \
                        urls="$$urls :" ; \
                        continue ; \
                elif [ -n "$$urls" -a -z "$(findstring :,$(CHAIN))" ]; then \
                        urls="$$urls :" ; \
                fi ; \
                rm -rf .tmp-$$$$ ; \
                mkdir -p .tmp-$$$$ ; \
                pushd .tmp-$$$$ > /dev/null ; \
                git clone -q --depth 1 git+https://src.koozali.org/$(GIT_ORG)/$$component.git $$component ; \
                urls="$$urls `make -s -C $$component/$$subdir giturl`" ; \
                popd > /dev/null ; \
                rm -rf .tmp-$$$$ ; \
        done ; \
        if [ -z "$(findstring :,$(CHAIN))" ]; then \
                urls="$$urls :" ; \
        fi ; \
        urls="$$urls `make -s giturl`" ; \
		$(eval CHAIN_TARGET := $(firstword $(TARGET))) ; \
        $(BUILD_CLIENT) chain-build $(BUILD_FLAGS) $(CHAIN_TARGET) $$urls

.PHONY: switch
## switch: Switch git branch
##     Usage: make switch <git branch>
switch:
ifeq ($(strip $(NEW_BRANCH)),)
	$(error Error: Please specify a git branch. Example: make switch sme12)
endif
	@git switch $(NEW_BRANCH)
# Turn the branch name into a dummy target so Make doesn't complain
%:
	@:
	
## new: "make new | less" to see what has changed since the last tag was assigned
new:
	-@git diff $$(git describe --tags --abbrev=0) 2>/dev/null || git diff --staged

# TODO rework or remove
# mop up, printing out exactly what was mopped.
## clean: Remove sources and srpm
clean :
	@echo "Running the %clean script of the rpmbuild..."
	-@$(RPM_WITH_DIRS) --clean --nodeps $(SPECFILE)
	#@for F in $(FULLSOURCEFILES); do \
  #              if test -e $$F ; then \
  #                      echo "Deleting $$F" ; /bin/rm -f $$F ; \
  #              fi; \
  #      done
	#@if test -d $(TMPCVS); then \
	#	echo "Deleting CVS dir $(TMPCVS)" ; \
	#	/bin/rm -rf $(TMPCVS); \
	#fi
	@if test -e $(SRCRPMDIR)/$(NAME)-$(VERSION)-$(RELEASE).src.rpm ; then \
		echo "Deleting $(SRCRPMDIR)/$(NAME)-$(VERSION)-$(RELEASE).src.rpm" ; \
		/bin/rm -f $(SRCRPMDIR)/$(NAME)-$(VERSION)-$(RELEASE).src.rpm ; \
        fi
	@rm -fv *~ clog
	@echo "Fully clean!"

# To prevent CVS noise due to changing file timestamps, upgrade
# to patchutils-0.2.23-3 or later, and add to ~/.cvspkgsrc:
#    FILTERDIFF := filterdiff --remove-timestamps
ifndef FILTERDIFF
FILTERDIFF := cat
endif

ifdef CVE
PATCHFILE := $(NAME)-$(VERSION)-CVE-$(CVE).patch
SUFFIX := cve$(shell echo $(CVE) | sed s/.*-//)
else
PATCHFILE := $(NAME)-$(VERSION)-$(SUFFIX).patch
endif

## patch: Create and add a gendiff patch file
##     Usage: patch SUFFIX=<suffix>
patch:
	@if test -z "$(SUFFIX)"; then echo "Must specify SUFFIX=whatever" ; exit 1; fi
	(cd $(RPM_BUILD_DIR)/.. && gendiff $(NAME)-$(VERSION) .$(SUFFIX) | $(FILTERDIFF)) > $(PATCHFILE) || true
	@if ! test -s $(PATCHFILE); then echo "Patch is empty!"; exit 1; fi
	@echo "Created $(PATCHFILE)"
	#@grep "$(PATCHFILE)" CVS/Entries >&/dev/null || cvs add -ko $(PATCHFILE) || true

# Recreates the patch file of specified suffix from the current working sources
# but keeping any comments at the top of file intact, and backing up the old copy
# with a '~' suffix.
## rediff: Recreates a gendiff patch file, retaining comments
##     Usage: rediff SUFFIX=<suffix>
rediff:
	@if test -z "$(SUFFIX)"; then echo "Must specify SUFFIX=whatever" ; exit 1; fi
	@if ! test -f "$(PATCHFILE)"; then echo "$(PATCHFILE) not found"; exit 1; fi
	@mv -f $(PATCHFILE) $(PATCHFILE)\~
	@sed '/^--- /,$$d' < $(PATCHFILE)\~ > $(PATCHFILE)
	@(cd $(RPM_BUILD_DIR)/.. && gendiff $(NAME)-$(VERSION) .$(SUFFIX) | $(FILTERDIFF)) >> $(PATCHFILE) || true

## clog: Make a clog file containing latest changelog entry
clog: $(SPECFILE)
	@sed -n '/^%changelog/,/^$$/p' $(SPECFILE) | sed '1d;/^$$/d;s/%%/%/g' | tee clog
	@cat clog

## commit: Commit and push to GIT using the clog file as the log message
commit: clog
	@git commit -F clog
	@rm -f clog
	@git push

## commitonly: Commit locally to GIT using the clog file as the log message
commitonly: clog
	@git commit -F clog
	@rm -f clog

## push: Push to GIT local commits (e.g. after git commit or make commitonly)
push:
	@git push

.PHONY: help
## help: Show this help message (also just make)
help:
	@echo "========================================================================="
	@echo "TARGET PARAMETER REVISION METHODOLOGY"
	@echo "========================================================================="
	@echo "  Your active Target parameter determines which SME/Contribs platform tags"
	@echo "  will be evaluated for build pipelines, tagging loops, and Koji uploads."
	@echo ""
	@echo "  How TARGET is computed:"
	@echo "    1. Manual Override: Pass it explicitly via CLI (e.g. make <command> TARGET=sme11)."
	@echo "    2. Feature Branch: If on an 'sme*' or 'contribs*' branch, TARGET auto-locks"
	@echo "                       directly to your current active git branch name."
	@echo "    3. Master Fallback: If on 'master' with a pristine repository workspace,"
	@echo "                       TARGET auto-expands into the complete version matrix"
	@echo "                       contained in 'common/current'."
	@echo ""
	@echo "  Current Workspace State:"
	@echo -e "    Active Git Branch: \033[32m$(GIT_BRANCH)\033[0m"
	@echo -e "    Assigned Targets:  \033[33m$(TARGET)\033[0m"
	@echo "========================================================================="
	@echo ""
	@echo "Available commands:"
	@echo ""
	@awk '/^## / { \
	    if (match($$0, /^## [a-zA-Z\-_0-9%]+:/)) { \
		currentCmd = substr($$0, 4, index($$0, ":") - 4); \
		helpMessage = substr($$0, index($$0, ":") + 2); \
		lineNum = 1000; \
		printf "%s|||%d|||  \033[36m%-16s\033[0m %s\n", currentCmd, lineNum, currentCmd, helpMessage; \
	    } else { \
		if (currentCmd != "") { \
		    lineNum++; \
		    detailMessage = substr($$0, 4); \
		    printf "%s|||%d|||                   %s\n", currentCmd, lineNum, detailMessage; \
		} \
	    } \
	}' $(MAKEFILE_LIST) | sort -t'|' -k1,1 -k2,2n | cut -d'|' -f7-

## gimmespec: Print the name of the specfile
gimmespec:
	@echo "$(SPECFILE)"

## unused-patches: Display list of patches not referenced by name in the specfile
unused-patches:
	@for f in *.patch; do if [ -e $$f ]; then grep -q $$f $(SPECFILE) || echo $$f; fi; done

unused-fedora-patches:
	@for f in *.patch; do if [ -e $$f ]; then (egrep -q "^Patch[[:digit:]]+:[[:space:]]+$$f" $(SPECFILE) || echo "Unused:    $$f") && egrep -q "^ApplyPatch[[:space:]]+$$f" $(SPECFILE) || echo "Unapplied: $$f"; fi; done

